"""OPTIMISE@Wits - local practice tester.

Put this file in the same folder as your solver.py and run:

    python optimise_local_test.py

It scores your solver on the eight public practice instances (P01-P08) using
exactly the code the competition platform runs, so a clean run here means a
clean submission. The official baseline scores about 37.77.

    python optimise_local_test.py --solver path/to/solver.py
    python optimise_local_test.py --quiet

DO NOT EDIT THIS FILE, and do not submit it. Submit only solver.py.

Generated by scripts/build_local_tester.py - do not edit by hand.
"""
from __future__ import annotations

import argparse
import ast
import builtins as _builtins
import copy
import importlib
import math
import sys
import time
import types
from dataclasses import dataclass
from pathlib import Path
from typing import Callable, Dict, Iterable, Optional, Tuple

import numpy as np


# --- from optimise.py -----------------------------------------------
class BudgetExceeded(RuntimeError):
    """Raised when an oracle call would exceed the evaluation budget."""


class GradientUnavailable(RuntimeError):
    """Raised when an exact gradient is not available for an instance."""


class InvalidPoint(ValueError):
    """Raised when an oracle receives a malformed or unsafe point."""

# --- from problem.py ------------------------------------------------
from typing import Callable, Optional

import numpy as np




class Problem:
    """A smooth unconstrained optimisation problem with a strict call budget."""

    SAFETY_LIMIT = 1.0e8

    def __init__(
        self,
        *,
        n: int,
        x0: np.ndarray,
        budget: int,
        seed: int,
        value_fn: Callable[[np.ndarray], float],
        gradient_fn: Optional[Callable[[np.ndarray], np.ndarray]] = None,
    ) -> None:
        if n <= 0:
            raise ValueError("n must be positive")
        if budget <= 0:
            raise ValueError("budget must be positive")
        self.n = int(n)
        self.x0 = self._coerce_point(x0).copy()
        self.budget = int(budget)
        self.seed = int(seed)
        self.has_gradient = gradient_fn is not None
        self._value_fn = value_fn
        self._gradient_fn = gradient_fn
        self._used = 0
        self._value_calls = 0
        self._gradient_calls = 0
        self._invalid_calls = 0

    @property
    def remaining(self) -> int:
        return self.budget - self._used

    @property
    def used(self) -> int:
        return self._used

    @property
    def value_calls(self) -> int:
        return self._value_calls

    @property
    def gradient_calls(self) -> int:
        return self._gradient_calls

    @property
    def invalid_calls(self) -> int:
        return self._invalid_calls

    def _coerce_point(self, x: np.ndarray) -> np.ndarray:
        try:
            arr = np.asarray(x, dtype=float)
        except Exception as exc:  # pragma: no cover - defensive
            raise InvalidPoint("point is not numeric") from exc
        if arr.ndim != 1 or arr.shape[0] != self.n:
            raise InvalidPoint(f"expected shape ({self.n},), received {arr.shape}")
        if not np.all(np.isfinite(arr)):
            raise InvalidPoint("point contains NaN or infinity")
        if np.max(np.abs(arr), initial=0.0) > self.SAFETY_LIMIT:
            raise InvalidPoint("point exceeds the numerical safety limit")
        return arr

    def _charge(self, units: int) -> None:
        if self.remaining < units:
            raise BudgetExceeded(
                f"oracle call costs {units} units but only {self.remaining} remain"
            )
        self._used += units

    def value(self, x: np.ndarray) -> float:
        try:
            arr = self._coerce_point(x)
        except InvalidPoint:
            self._invalid_calls += 1
            raise
        self._charge(1)
        self._value_calls += 1
        value = float(self._value_fn(arr.copy()))
        if not np.isfinite(value):
            raise InvalidPoint("objective returned a non-finite value")
        return value

    def gradient(self, x: np.ndarray) -> np.ndarray:
        if self._gradient_fn is None:
            raise GradientUnavailable("this instance does not expose a gradient")
        try:
            arr = self._coerce_point(x)
        except InvalidPoint:
            self._invalid_calls += 1
            raise
        self._charge(2)
        self._gradient_calls += 1
        grad = np.asarray(self._gradient_fn(arr.copy()), dtype=float)
        if grad.shape != (self.n,):
            raise RuntimeError("internal benchmark gradient has the wrong shape")
        if not np.all(np.isfinite(grad)):
            raise InvalidPoint("gradient returned a non-finite value")
        return grad.copy()

    def evaluate_untimed(self, x: np.ndarray) -> float:
        """Evaluate the objective without charging the budget (organiser only)."""
        return float(self._value_fn(self._coerce_point(x)))


class SolverView:
    """Marker base class for the object passed to ``solve(problem)``."""

    __slots__ = ()


def make_view(problem: Problem) -> SolverView:
    """Return the restricted problem object handed to a team solver.

    Every member documented in the API specification is present. ``problem`` is
    captured in a closure rather than stored as an attribute, so there is no
    ``_value_fn`` or ``_problem`` attribute for a submission to discover.
    """

    class _View(SolverView):
        __slots__ = ()

        n = problem.n
        budget = problem.budget
        seed = problem.seed
        has_gradient = problem.has_gradient
        x0 = problem.x0.copy()

        @property
        def remaining(self) -> int:
            return problem.remaining

        @property
        def used(self) -> int:
            return problem.used

        @property
        def value_calls(self) -> int:
            return problem.value_calls

        @property
        def gradient_calls(self) -> int:
            return problem.gradient_calls

        def value(self, x):
            return problem.value(x)

        def gradient(self, x):
            return problem.gradient(x)

        def __repr__(self) -> str:
            return f"<Problem n={problem.n} budget={problem.budget}>"

    return _View()

# --- from benchmarks.py ---------------------------------------------
from dataclasses import dataclass
from typing import Callable, Dict, Tuple

import numpy as np


Array = np.ndarray
BaseFunction = Callable[[Array], float]
BaseGradient = Callable[[Array], Array]




@dataclass(frozen=True)
class ReferenceData:
    instance_id: str
    family: str
    x_star: Array
    reference_value: float
    initial_value: float


@dataclass(frozen=True)
class BaseSpec:
    value: BaseFunction
    gradient: BaseGradient
    optimum_y: Array
    optimum_value: float
    initial_y: Array


def _orthogonal(n: int, rng: np.random.Generator) -> Array:
    q, r = np.linalg.qr(rng.normal(size=(n, n)))
    signs = np.sign(np.diag(r))
    signs[signs == 0.0] = 1.0
    return q @ np.diag(signs)


def _sphere(n: int, rng: np.random.Generator) -> BaseSpec:
    y0 = rng.normal(size=n) * 4.0
    return BaseSpec(
        value=lambda y: 0.5 * float(y @ y),
        gradient=lambda y: y.copy(),
        optimum_y=np.zeros(n),
        optimum_value=0.0,
        initial_y=y0,
    )


def _rosenbrock(n: int, rng: np.random.Generator) -> BaseSpec:
    if n < 2:
        raise ValueError("Rosenbrock requires n >= 2")

    def value(y: Array) -> float:
        return float(np.sum(100.0 * (y[1:] - y[:-1] ** 2) ** 2 + (1.0 - y[:-1]) ** 2))

    def gradient(y: Array) -> Array:
        g = np.zeros_like(y)
        g[:-1] += -400.0 * y[:-1] * (y[1:] - y[:-1] ** 2) - 2.0 * (1.0 - y[:-1])
        g[1:] += 200.0 * (y[1:] - y[:-1] ** 2)
        return g

    y0 = np.ones(n)
    y0[::2] = -1.2
    return BaseSpec(value, gradient, np.ones(n), 0.0, y0)


def _powell(n: int, rng: np.random.Generator) -> BaseSpec:
    if n % 4 != 0:
        raise ValueError("Powell dimension must be a multiple of four")

    def value(y: Array) -> float:
        z = y.reshape(-1, 4)
        t1 = z[:, 0] + 10.0 * z[:, 1]
        t2 = z[:, 2] - z[:, 3]
        t3 = z[:, 1] - 2.0 * z[:, 2]
        t4 = z[:, 0] - z[:, 3]
        return float(np.sum(t1**2 + 5.0 * t2**2 + t3**4 + 10.0 * t4**4))

    def gradient(y: Array) -> Array:
        z = y.reshape(-1, 4)
        g = np.zeros_like(z)
        t1 = z[:, 0] + 10.0 * z[:, 1]
        t2 = z[:, 2] - z[:, 3]
        t3 = z[:, 1] - 2.0 * z[:, 2]
        t4 = z[:, 0] - z[:, 3]
        g[:, 0] = 2.0 * t1 + 40.0 * t4**3
        g[:, 1] = 20.0 * t1 + 4.0 * t3**3
        g[:, 2] = 10.0 * t2 - 8.0 * t3**3
        g[:, 3] = -10.0 * t2 - 40.0 * t4**3
        return g.reshape(-1)

    y0 = np.tile(np.array([3.0, -1.0, 0.0, 1.0]), n // 4)
    return BaseSpec(value, gradient, np.zeros(n), 0.0, y0)


def _wood(n: int, rng: np.random.Generator) -> BaseSpec:
    if n % 4 != 0:
        raise ValueError("Wood dimension must be a multiple of four")

    def value(y: Array) -> float:
        z = y.reshape(-1, 4)
        x1, x2, x3, x4 = z.T
        block = (
            100.0 * (x2 - x1**2) ** 2
            + (1.0 - x1) ** 2
            + 90.0 * (x4 - x3**2) ** 2
            + (1.0 - x3) ** 2
            + 10.1 * ((x2 - 1.0) ** 2 + (x4 - 1.0) ** 2)
            + 19.8 * (x2 - 1.0) * (x4 - 1.0)
        )
        return float(np.sum(block))

    def gradient(y: Array) -> Array:
        z = y.reshape(-1, 4)
        x1, x2, x3, x4 = z.T
        g = np.empty_like(z)
        g[:, 0] = -400.0 * x1 * (x2 - x1**2) - 2.0 * (1.0 - x1)
        g[:, 1] = 200.0 * (x2 - x1**2) + 20.2 * (x2 - 1.0) + 19.8 * (x4 - 1.0)
        g[:, 2] = -360.0 * x3 * (x4 - x3**2) - 2.0 * (1.0 - x3)
        g[:, 3] = 180.0 * (x4 - x3**2) + 20.2 * (x4 - 1.0) + 19.8 * (x2 - 1.0)
        return g.reshape(-1)

    y0 = np.tile(np.array([-3.0, -1.0, -3.0, -1.0]), n // 4)
    return BaseSpec(value, gradient, np.ones(n), 0.0, y0)


def _ripple(n: int, rng: np.random.Generator) -> BaseSpec:
    def value(y: Array) -> float:
        return float(np.sum(y**2 + 0.10 * (1.0 - np.cos(5.0 * y))))

    def gradient(y: Array) -> Array:
        return 2.0 * y + 0.5 * np.sin(5.0 * y)

    y0 = rng.uniform(-4.0, 4.0, size=n)
    return BaseSpec(value, gradient, np.zeros(n), 0.0, y0)


def _twisted_quartic(n: int, rng: np.random.Generator) -> BaseSpec:
    def value(y: Array) -> float:
        coupling = 0.05 * np.sum((y[1:] - y[:-1]) ** 2)
        return float(np.sum((y**2 - 1.0) ** 2) + coupling)

    def gradient(y: Array) -> Array:
        g = 4.0 * y * (y**2 - 1.0)
        if n > 1:
            diff = y[1:] - y[:-1]
            g[:-1] -= 0.10 * diff
            g[1:] += 0.10 * diff
        return g

    y0 = rng.normal(scale=0.35, size=n)
    return BaseSpec(value, gradient, np.ones(n), 0.0, y0)


def _styblinski(n: int, rng: np.random.Generator) -> BaseSpec:
    optimum_scalar = -2.903534027771178
    optimum_value = -39.16616570377142 * n

    def value(y: Array) -> float:
        return float(0.5 * np.sum(y**4 - 16.0 * y**2 + 5.0 * y))

    def gradient(y: Array) -> Array:
        return 2.0 * y**3 - 16.0 * y + 2.5

    y0 = rng.uniform(-1.0, 3.5, size=n)
    return BaseSpec(
        value,
        gradient,
        np.full(n, optimum_scalar),
        optimum_value,
        y0,
    )


def _plateau(n: int, rng: np.random.Generator) -> BaseSpec:
    eps = 1.0e-4

    def value(y: Array) -> float:
        return float(np.sum(np.sqrt(y**2 + eps) - np.sqrt(eps)))

    def gradient(y: Array) -> Array:
        return y / np.sqrt(y**2 + eps)

    y0 = rng.normal(size=n) * 5.0
    return BaseSpec(value, gradient, np.zeros(n), 0.0, y0)


def _himmelblau(n: int, rng: np.random.Generator) -> BaseSpec:
    if n != 2:
        raise ValueError("Himmelblau is two-dimensional")

    def value(y: Array) -> float:
        a = y[0] ** 2 + y[1] - 11.0
        b = y[0] + y[1] ** 2 - 7.0
        return float(a**2 + b**2)

    def gradient(y: Array) -> Array:
        a = y[0] ** 2 + y[1] - 11.0
        b = y[0] + y[1] ** 2 - 7.0
        return np.array([4.0 * y[0] * a + 2.0 * b, 2.0 * a + 4.0 * y[1] * b])

    # One known global minimiser; the transformed function retains several.
    optimum = np.array([3.0, 2.0])
    y0 = np.array([-4.0, 0.0])
    return BaseSpec(value, gradient, optimum, 0.0, y0)


_BUILDERS: Dict[str, Callable[[int, np.random.Generator], BaseSpec]] = {
    "quadratic": _sphere,
    "rosenbrock": _rosenbrock,
    "powell": _powell,
    "wood": _wood,
    "ripple": _ripple,
    "twisted_quartic": _twisted_quartic,
    "styblinski": _styblinski,
    "plateau": _plateau,
    "himmelblau": _himmelblau,
}


def build_problem(config: dict) -> Tuple[Problem, ReferenceData]:
    """Construct a student-facing Problem and staff-only reference data."""
    family = str(config["family"])
    n = int(config["n"])
    seed = int(config["seed"])
    budget = int(config["budget"])
    provide_gradient = bool(config.get("gradient", True))
    condition = float(config.get("condition", 1.0))
    amplitude = float(config.get("amplitude", 1.0))
    offset = float(config.get("offset", 0.0))
    rotation = bool(config.get("rotation", True))
    shift_scale = float(config.get("shift_scale", 2.0))

    rng = np.random.default_rng(seed)
    if family not in _BUILDERS:
        raise KeyError(f"unknown benchmark family: {family}")
    base = _BUILDERS[family](n, rng)

    q = _orthogonal(n, rng) if rotation else np.eye(n)
    if condition <= 1.0:
        scales = np.ones(n)
    else:
        scales = np.geomspace(1.0, np.sqrt(condition), n)
        rng.shuffle(scales)
    a_matrix = np.diag(scales) @ q
    shift = rng.normal(scale=shift_scale, size=n)

    def to_y(x: Array) -> Array:
        return a_matrix @ (x - shift)

    def value_fn(x: Array) -> float:
        return amplitude * base.value(to_y(x)) + offset

    def gradient_fn(x: Array) -> Array:
        return amplitude * a_matrix.T @ base.gradient(to_y(x))

    x_star = shift + np.linalg.solve(a_matrix, base.optimum_y)
    x0 = shift + np.linalg.solve(a_matrix, base.initial_y)
    f_star = amplitude * base.optimum_value + offset
    f0 = value_fn(x0)
    instance_id = str(config["id"])
    reference = ReferenceData(
        instance_id=instance_id,
        family=family,
        x_star=x_star.copy(),
        reference_value=float(f_star),
        initial_value=float(f0),
    )

    problem = Problem(
        n=n,
        x0=x0,
        budget=budget,
        seed=seed + 100_003,
        value_fn=value_fn,
        gradient_fn=gradient_fn if provide_gradient else None,
    )
    return problem, reference

# --- from scoring.py ------------------------------------------------
import math
from typing import Iterable

import numpy as np

EPS = 1.0e-12


def instance_score(*, f0: float, f_star: float, f_final: float,
                   used: int, budget: int, valid: bool) -> dict:
    if not valid or not all(map(math.isfinite, (f0, f_star, f_final))):
        return {"quality": 0.0, "efficiency": 0.0, "score": 0.0, "accurate": False}
    g0 = max(float(f0 - f_star), EPS)
    gt = max(float(f_final - f_star), EPS)
    log_progress = math.log10(g0 / gt)
    quality = float(np.clip(log_progress / 8.0, 0.0, 1.0))
    efficiency = quality * max(0.0, 1.0 - float(used) / max(float(budget), 1.0))
    score = 95.0 * quality + 5.0 * efficiency
    return {
        "quality": quality,
        "efficiency": efficiency,
        "score": score,
        "accurate": quality >= 0.90,
    }


def aggregate_scores(instance_results: Iterable[dict]) -> dict:
    rows = list(instance_results)
    if not rows:
        return {
            "overall": 0.0,
            "mean": 0.0,
            "lower_quartile": 0.0,
            "valid_instances": 0,
            "accurate_instances": 0,
            "total_used": 0,
        }
    scores = np.array([float(r.get("score", 0.0)) for r in rows], dtype=float)
    mean = float(np.mean(scores))
    lower_quartile = float(np.quantile(scores, 0.25))
    overall = 0.8 * mean + 0.2 * lower_quartile
    return {
        "overall": overall,
        "mean": mean,
        "lower_quartile": lower_quartile,
        "valid_instances": sum(bool(r.get("valid", False)) for r in rows),
        "accurate_instances": sum(bool(r.get("accurate", False)) for r in rows),
        "total_used": sum(int(r.get("used", 0)) for r in rows),
    }

# --- from sandbox.py ------------------------------------------------
import ast
import builtins as _builtins
import importlib
import types
from pathlib import Path



class SubmissionError(RuntimeError):
    """Raised when a submission cannot be loaded or violates the rules."""


# --------------------------------------------------------------------------
# Import policy
# --------------------------------------------------------------------------

#: Modules a solver is allowed to import. Everything else raises ImportError.
ALLOWED_MODULES = frozenset(
    {
        "__future__",
        "numpy",
        "math",
        "cmath",
        "time",
        "random",
        "itertools",
        "functools",
        "operator",
        "collections",
        "heapq",
        "bisect",
        "copy",
        "dataclasses",
        "typing",
        "enum",
        "abc",
        "numbers",
        "statistics",
        "fractions",
        "decimal",
        "array",
        "string",
        "warnings",
        "contextlib",
        # Exception shims named in the API specification.
        "optimise",
        "Framework",
        "Framework.optimise",
    }
)

#: NumPy sub-packages that re-expose the operating system or the import system.
_BLOCKED_NUMPY_SUBMODULES = frozenset(
    {
        "numpy.ctypeslib",
        "numpy.distutils",
        "numpy.f2py",
        "numpy.testing",
    }
)

#: Reported verbatim to the team when the static screen trips.
_BLOCKED_MODULE_HINT = (
    "only the standard library subset listed in the API specification and NumPy "
    "may be imported"
)


def _module_allowed(name: str) -> bool:
    root = name.split(".")[0]
    if root == "numpy":
        return name not in _BLOCKED_NUMPY_SUBMODULES
    if root == "collections":  # collections.abc only
        return name in {"collections", "collections.abc"}
    if root == "Framework":
        return name in {"Framework", "Framework.optimise"}
    return name in ALLOWED_MODULES


def _restricted_import(name, globals=None, locals=None, fromlist=(), level=0):
    if level != 0:
        raise ImportError("relative imports are not permitted in solver.py")
    if not _module_allowed(name):
        raise ImportError(f"import of '{name}' is not permitted; {_BLOCKED_MODULE_HINT}")
    module = importlib.import_module(name)
    if fromlist:
        for item in fromlist:
            candidate = f"{name}.{item}"
            if isinstance(item, str) and not hasattr(module, item):
                if not _module_allowed(candidate):
                    raise ImportError(
                        f"import of '{candidate}' is not permitted; {_BLOCKED_MODULE_HINT}"
                    )
                importlib.import_module(candidate)
        return module
    # ``import a.b`` binds the root package.
    return importlib.import_module(name.split(".")[0])


# --------------------------------------------------------------------------
# Builtins policy
# --------------------------------------------------------------------------

_ALLOWED_BUILTINS = (
    # Types and constructors
    "bool int float complex str bytes bytearray list tuple dict set frozenset "
    "object type slice range enumerate reversed zip map filter iter next "
    # Numeric and sequence helpers
    "abs all any divmod hash len max min pow round sum sorted format repr "
    "chr ord hex oct bin ascii "
    # Class machinery
    "isinstance issubclass callable property staticmethod classmethod super "
    "__build_class__ "
    # Output
    "print "
    # Exceptions
    "BaseException Exception ArithmeticError ArithmeticError AssertionError "
    "AttributeError EOFError FloatingPointError GeneratorExit ImportError "
    "IndentationError IndexError KeyError KeyboardInterrupt LookupError "
    "MemoryError NameError NotImplementedError OverflowError RecursionError "
    "ReferenceError RuntimeError StopIteration StopAsyncIteration SyntaxError "
    "TypeError UnboundLocalError UnicodeDecodeError UnicodeEncodeError "
    "UnicodeError ValueError ZeroDivisionError Warning UserWarning "
    "RuntimeWarning DeprecationWarning "
    # Constants
    "True False None NotImplemented Ellipsis"
).split()

#: Never exposed: open, eval, exec, compile, input, breakpoint, help, exit,
#: quit, globals, locals, vars, dir, setattr, delattr, memoryview, id,
#: __loader__, __spec__.


def _safe_getattr(obj, name, *default):
    if isinstance(name, str) and name.startswith("_"):
        raise AttributeError(f"access to private attribute '{name}' is not permitted")
    return getattr(obj, name, *default)


def _safe_hasattr(obj, name):
    if isinstance(name, str) and name.startswith("_"):
        return False
    return hasattr(obj, name)


def _build_restricted_builtins() -> dict:
    namespace = {}
    for name in _ALLOWED_BUILTINS:
        if hasattr(_builtins, name):
            namespace[name] = getattr(_builtins, name)
    namespace["__import__"] = _restricted_import
    namespace["getattr"] = _safe_getattr
    namespace["hasattr"] = _safe_hasattr
    return namespace


# --------------------------------------------------------------------------
# Static screen
# --------------------------------------------------------------------------

#: Dunder names a solver may legitimately mention.
_ALLOWED_DUNDERS = frozenset({"__future__", "__name__", "__main__", "__init__",
                              "__repr__", "__str__", "__len__", "__call__",
                              "__eq__", "__lt__", "__hash__", "__iter__",
                              "__next__", "__enter__", "__exit__", "__doc__"})

_FORBIDDEN_NAMES = frozenset(
    {"open", "eval", "exec", "compile", "input", "breakpoint", "globals",
     "locals", "vars", "dir", "setattr", "delattr", "memoryview", "help",
     "exit", "quit", "__import__"}
)

#: File-system entry points reachable through NumPy. None of these has a
#: legitimate use inside a solver, and every one of them could be pointed at the
#: hidden benchmark configuration files.
_FORBIDDEN_ATTRIBUTES = frozenset(
    {"load", "loadtxt", "genfromtxt", "fromfile", "fromregex", "memmap",
     "DataSource", "save", "savez", "savez_compressed", "savetxt", "tofile",
     "dump", "dumps"}
)

#: (module name, attribute) pairs neutralised by :func:`harden_numpy`.
_NUMPY_IO_TARGETS = (
    ("numpy", "load"),
    ("numpy", "loadtxt"),
    ("numpy", "genfromtxt"),
    ("numpy", "fromfile"),
    ("numpy", "fromregex"),
    ("numpy", "memmap"),
    ("numpy", "save"),
    ("numpy", "savez"),
    ("numpy", "savez_compressed"),
    ("numpy", "savetxt"),
    ("numpy.lib", "load"),
    ("numpy.lib", "loadtxt"),
    ("numpy.lib", "genfromtxt"),
    ("numpy.lib", "save"),
    ("numpy.lib", "savetxt"),
    ("numpy.lib.npyio", "load"),
    ("numpy.lib.npyio", "loadtxt"),
    ("numpy.lib.npyio", "genfromtxt"),
    ("numpy.lib.npyio", "save"),
    ("numpy.lib.npyio", "savetxt"),
)


def _blocked_io(*_args, **_kwargs):
    raise PermissionError("file access is not permitted inside a solver")


def harden_numpy() -> None:
    """Neutralise NumPy's file-reading and file-writing entry points.

    Called once by the ingestion program before any submission is executed. The
    evaluation engine never uses these functions, so replacing them has no
    effect on scoring.
    """
    import sys

    for module_name, attribute in _NUMPY_IO_TARGETS:
        module = sys.modules.get(module_name)
        if module is not None and hasattr(module, attribute):
            try:
                setattr(module, attribute, _blocked_io)
            except Exception:  # pragma: no cover - read-only module attribute
                pass


def static_check(path: str | Path) -> list[str]:
    """Screen a submission and return a list of human-readable rule violations."""
    text = Path(path).read_text(encoding="utf-8", errors="replace")
    issues: list[str] = []
    try:
        tree = ast.parse(text, filename="solver.py")
    except SyntaxError as exc:
        return [f"syntax error on line {exc.lineno}: {exc.msg}"]

    solve_found = any(
        isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)) and node.name == "solve"
        for node in tree.body
    )
    if not solve_found:
        issues.append("no top-level function named solve(problem) was found")

    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            for alias in node.names:
                if not _module_allowed(alias.name):
                    issues.append(f"line {node.lineno}: prohibited import '{alias.name}'")
        elif isinstance(node, ast.ImportFrom):
            module = node.module or ""
            if node.level != 0:
                issues.append(f"line {node.lineno}: relative imports are not permitted")
            elif not _module_allowed(module):
                issues.append(f"line {node.lineno}: prohibited import '{module}'")
        elif isinstance(node, ast.Name):
            if node.id in _FORBIDDEN_NAMES:
                issues.append(f"line {node.lineno}: prohibited use of '{node.id}'")
            elif _is_private_dunder(node.id):
                issues.append(f"line {node.lineno}: prohibited use of '{node.id}'")
        elif isinstance(node, ast.Attribute):
            if _is_private_dunder(node.attr):
                issues.append(f"line {node.lineno}: prohibited attribute '.{node.attr}'")
            elif node.attr in _FORBIDDEN_ATTRIBUTES:
                issues.append(
                    f"line {node.lineno}: prohibited file-access call '.{node.attr}()'"
                )
            elif node.attr.startswith("_") and not node.attr.startswith("__"):
                # Single-underscore helpers defined by the team are fine; reaching
                # into a private attribute of the problem object is not.
                if isinstance(node.value, ast.Name) and node.value.id in {
                    "problem", "prob", "p"
                }:
                    issues.append(
                        f"line {node.lineno}: prohibited access to private member "
                        f"'{node.value.id}.{node.attr}'"
                    )
    return sorted(set(issues))


def _is_private_dunder(name: str) -> bool:
    return name.startswith("__") and name.endswith("__") and name not in _ALLOWED_DUNDERS


# --------------------------------------------------------------------------
# Loading
# --------------------------------------------------------------------------


def load_student_solver(path: str | Path, *, enforce: bool = True):
    """Compile and execute ``solver.py`` in a restricted namespace.

    Returns the team's ``solve`` callable. Raises :class:`SubmissionError` with a
    message that is safe to show to the team.
    """
    solver_path = Path(path)
    if not solver_path.is_file():
        raise SubmissionError(f"solver.py was not found at {solver_path.name}")

    if enforce:
        issues = static_check(solver_path)
        if issues:
            raise SubmissionError("submission rejected by the rule check: " + "; ".join(issues))

    source = solver_path.read_text(encoding="utf-8", errors="replace")
    try:
        code = compile(source, "solver.py", "exec")
    except SyntaxError as exc:
        raise SubmissionError(f"syntax error on line {exc.lineno}: {exc.msg}") from exc

    module = types.ModuleType("team_solver")
    module.__dict__["__name__"] = "team_solver"
    module.__dict__["__file__"] = "solver.py"
    if enforce:
        module.__dict__["__builtins__"] = _build_restricted_builtins()

    # dataclasses and typing resolve annotations through sys.modules[cls.__module__],
    # so the module must be registered. "team_solver" is not an importable name
    # under the restricted import hook, so this grants the submission nothing.
    import sys

    sys.modules["team_solver"] = module

    try:
        exec(code, module.__dict__)  # noqa: S102 - deliberate, sandboxed above
    except Exception as exc:
        raise SubmissionError(f"solver.py failed while being imported: {type(exc).__name__}: {exc}") from exc

    solve = module.__dict__.get("solve")
    if not callable(solve):
        raise SubmissionError("solver.py must define a callable solve(problem)")
    return solve



# ---------------------------------------------------------------------------
# Make both documented import styles work inside a team's solver.py, exactly as
# they do on the platform:
#     from optimise import BudgetExceeded
#     from Framework.optimise import BudgetExceeded
# ---------------------------------------------------------------------------

def _install_import_shims() -> None:
    shim = types.ModuleType("optimise")
    for name in ("BudgetExceeded", "GradientUnavailable", "InvalidPoint"):
        setattr(shim, name, globals()[name])
    sys.modules["optimise"] = shim

    package = types.ModuleType("Framework")
    package.__path__ = []
    inner = types.ModuleType("Framework.optimise")
    for name in ("BudgetExceeded", "GradientUnavailable", "InvalidPoint"):
        setattr(inner, name, globals()[name])
    package.optimise = inner
    sys.modules["Framework"] = package
    sys.modules["Framework.optimise"] = inner


PUBLIC_INSTANCES = [
    {
        "id": "P01",
        "family": "quadratic",
        "n": 5,
        "seed": 101,
        "budget": 550,
        "gradient": True,
        "condition": 10.0,
        "amplitude": 1.0,
        "offset": 0.0,
        "rotation": True,
        "shift_scale": 2.0
    },
    {
        "id": "P02",
        "family": "quadratic",
        "n": 12,
        "seed": 102,
        "budget": 1200,
        "gradient": False,
        "condition": 10000.0,
        "amplitude": 1.0,
        "offset": 0.0,
        "rotation": True,
        "shift_scale": 2.0
    },
    {
        "id": "P03",
        "family": "rosenbrock",
        "n": 4,
        "seed": 103,
        "budget": 880,
        "gradient": True,
        "condition": 4.0,
        "amplitude": 1.0,
        "offset": 0.0,
        "rotation": True,
        "shift_scale": 2.0
    },
    {
        "id": "P04",
        "family": "powell",
        "n": 8,
        "seed": 104,
        "budget": 1440,
        "gradient": False,
        "condition": 9.0,
        "amplitude": 1.0,
        "offset": 0.0,
        "rotation": True,
        "shift_scale": 2.0
    },
    {
        "id": "P05",
        "family": "ripple",
        "n": 6,
        "seed": 105,
        "budget": 960,
        "gradient": True,
        "condition": 16.0,
        "amplitude": 1.0,
        "offset": 0.0,
        "rotation": True,
        "shift_scale": 2.0
    },
    {
        "id": "P06",
        "family": "twisted_quartic",
        "n": 8,
        "seed": 106,
        "budget": 1520,
        "gradient": False,
        "condition": 9.0,
        "amplitude": 1.0,
        "offset": 0.0,
        "rotation": True,
        "shift_scale": 2.0
    },
    {
        "id": "P07",
        "family": "plateau",
        "n": 10,
        "seed": 107,
        "budget": 1400,
        "gradient": True,
        "condition": 100.0,
        "amplitude": 1.0,
        "offset": 0.0,
        "rotation": True,
        "shift_scale": 2.0
    },
    {
        "id": "P08",
        "family": "himmelblau",
        "n": 2,
        "seed": 108,
        "budget": 500,
        "gradient": False,
        "condition": 4.0,
        "amplitude": 1.0,
        "offset": 0.0,
        "rotation": True,
        "shift_scale": 2.0
    }
]


def main() -> int:
    here = Path(__file__).resolve().parent
    parser = argparse.ArgumentParser(
        description="Score your solver on the public practice suite (P01-P08).")
    parser.add_argument("--solver", default=None,
                        help="path to your solver.py (default: solver.py next to this file)")
    parser.add_argument("--quiet", action="store_true", help="print the summary only")
    parser.add_argument("--no-rule-check", action="store_true",
                        help="skip the import rule check (the platform will still apply it)")
    args = parser.parse_args()

    if args.solver:
        solver = Path(args.solver)
        if not solver.is_file():
            solver = here / args.solver
    else:
        solver = here / "solver.py"
    if not solver.is_file():
        print(f"Could not find solver.py.\nLooked for: {solver}", file=sys.stderr)
        print("Put this file in the same folder as your solver.py, or pass --solver.",
              file=sys.stderr)
        return 2

    _install_import_shims()
    if not args.no_rule_check:
        harden_numpy()

    try:
        solve = load_student_solver(solver, enforce=not args.no_rule_check)
    except SubmissionError as exc:
        print("Your solver was REJECTED by the competition rule check:\n", file=sys.stderr)
        print(f"    {exc}\n", file=sys.stderr)
        print("The platform applies the same check, so fix this before submitting.",
              file=sys.stderr)
        return 1

    rows = []
    started = time.time()
    for config in PUBLIC_INSTANCES:
        problem, reference = build_problem(config)
        view = make_view(problem)
        error, f_final, valid = "", float("inf"), False
        try:
            raw = solve(view)
            if not isinstance(raw, dict):
                raise TypeError("solve(problem) must return a dictionary")
            missing = {"x", "status", "method"} - set(raw)
            if missing:
                raise KeyError(f"missing return keys: {sorted(missing)}")
            x = np.asarray(raw["x"], dtype=float)
            if x.shape != (problem.n,):
                raise ValueError(
                    f"result['x'] must have shape ({problem.n},), got {x.shape}")
            f_final = problem.evaluate_untimed(x)
            if not np.isfinite(f_final):
                raise ValueError("the objective at your returned point is not finite")
            valid = True
        except Exception as exc:
            error = f"{type(exc).__name__}: {exc}"

        info = instance_score(f0=reference.initial_value,
                              f_star=reference.reference_value,
                              f_final=f_final, used=problem.used,
                              budget=problem.budget, valid=valid)
        rows.append({"instance_id": reference.instance_id, "family": reference.family,
                     "n": problem.n, "budget": problem.budget, "used": problem.used,
                     "valid": valid, "error": error, **info})

    summary = aggregate_scores(rows)
    elapsed = time.time() - started

    if not args.quiet:
        print(f"{'id':<5}{'family':<17}{'n':>3}{'budget':>8}{'used':>7}"
              f"{'valid':>7}{'quality':>9}{'score':>8}  note")
        for r in rows:
            note = r["error"] or ("high accuracy" if r["accurate"] else "")
            print(f"{r['instance_id']:<5}{r['family']:<17}{r['n']:>3}{r['budget']:>8}"
                  f"{r['used']:>7}{'yes' if r['valid'] else 'NO':>7}"
                  f"{r['quality']:>9.3f}{r['score']:>8.2f}  {note}")
        print()

    print("OPTIMISE@Wits public practice suite (P01-P08)")
    print(f"  Overall score:       {summary['overall']:.2f}")
    print(f"  Mean instance score: {summary['mean']:.2f}")
    print(f"  Lower quartile:      {summary['lower_quartile']:.2f}")
    print(f"  Valid instances:     {summary['valid_instances']}/{len(rows)}")
    print(f"  High accuracy:       {summary['accurate_instances']}/{len(rows)}")
    print(f"  Time taken:          {elapsed:.1f}s")

    if summary["valid_instances"] < len(rows):
        print("\nSome instances are INVALID. An invalid instance scores zero on the")
        print("platform too, so fix these before you submit.")
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
